import React, { useState } from "react";
import { 
  Wrench, BookOpen, Scissors, PlusCircle, MinusCircle, 
  FilePlus, Trash2, CheckCircle2, Copy, Sparkles, ArrowRight,
  Code2, Lightbulb, Play, Eye, FileText, Check, ShieldCheck
} from "lucide-react";
import { AGENT_SKILLS_REGISTRY, TOOL_SELECTION_RULES, AgentSkill } from "../services/agentSkillsService";
import { VirtualFile } from "../types";

interface AgentSkillsInspectorProps {
  files: VirtualFile[];
  onApplyOperator: (operatorSnippet: string, actionLabel: string) => void;
  onAddLog?: (type: any, msg: string) => void;
  theme: "light" | "dark";
}

export const AgentSkillsInspector: React.FC<AgentSkillsInspectorProps> = ({
  files,
  onApplyOperator,
  onAddLog,
  theme
}) => {
  const isDark = theme === "dark";
  const [activeTab, setActiveTab] = useState<"skills" | "matrix" | "playground">("skills");
  const [selectedSkillId, setSelectedSkillId] = useState<string>("skill_surgical_edit");
  const [copiedId, setCopiedId] = useState<string | null>(null);

  // Playground simulation state
  const [simTargetFile, setSimTargetFile] = useState<string>(files[0]?.path || "src/types.ts");
  const [simOperation, setSimOperation] = useState<"read" | "edit" | "add" | "remove" | "create">("add");
  const [simCustomSnippet, setSimCustomSnippet] = useState<string>("");
  const [simSuccessMsg, setSimSuccessMsg] = useState<string | null>(null);

  const selectedSkill = AGENT_SKILLS_REGISTRY.find(s => s.id === selectedSkillId) || AGENT_SKILLS_REGISTRY[1];

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const generateSimulationSnippet = () => {
    switch (simOperation) {
      case "read":
        return `<read_file path="${simTargetFile}" />`;
      case "add":
        return `<add_content path="${simTargetFile}" position="end">
// Added via AI Agent Add Content Skill
export const AGENT_ENABLED = true;
</add_content>`;
      case "remove":
        return `<remove_content path="${simTargetFile}">
// Added via AI Agent Add Content Skill
export const AGENT_ENABLED = true;
</remove_content>`;
      case "edit":
        return `<edit_file path="${simTargetFile}">
  <search>
// target search snippet
  </search>
  <replace>
// updated replacement snippet
  </replace>
</edit_file>`;
      case "create":
        return `<create_file path="src/utils/agentHelper.ts">
/**
 * Generated by Agentic AI with Complete Implementation
 */
export function calculateExecutionDiff(start: number, end: number): number {
  return Math.max(0, end - start);
}
</create_file>`;
    }
  };

  const handleRunPlaygroundAction = () => {
    const snippetToRun = simCustomSnippet.trim() || generateSimulationSnippet();
    onApplyOperator(snippetToRun, `Agent Skill [${simOperation.toUpperCase()}]`);
    setSimSuccessMsg(`Operator applied to workspace! Check the editor.`);
    if (onAddLog) {
      onAddLog("success", `AI Agent successfully executed skill: ${simOperation} on workspace!`);
    }
    setTimeout(() => setSimSuccessMsg(null), 4000);
  };

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case "read": return <BookOpen className="w-4 h-4 text-sky-400" />;
      case "edit": return <Scissors className="w-4 h-4 text-amber-400" />;
      case "add": return <PlusCircle className="w-4 h-4 text-emerald-400" />;
      case "remove": return <MinusCircle className="w-4 h-4 text-rose-400" />;
      case "create": return <FilePlus className="w-4 h-4 text-purple-400" />;
      case "manage": return <Trash2 className="w-4 h-4 text-zinc-400" />;
      default: return <Wrench className="w-4 h-4 text-blue-400" />;
    }
  };

  return (
    <div className={`rounded-2xl border flex flex-col h-full overflow-hidden ${
      isDark ? "bg-zinc-950 border-zinc-800 text-zinc-100" : "bg-white border-zinc-200 text-zinc-900"
    }`}>
      {/* Header Banner */}
      <div className={`p-5 border-b flex flex-wrap items-center justify-between gap-4 ${
        isDark ? "bg-zinc-900/60 border-zinc-800" : "bg-zinc-50 border-zinc-200"
      }`}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-indigo-500 to-cyan-400 flex items-center justify-center text-white shadow-md">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-bold text-base tracking-tight">AI Agent Skills & Tool Selection Intelligence</h3>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-mono font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/30">
                Agentic v2.0 Active
              </span>
            </div>
            <p className="text-xs text-zinc-400 mt-0.5">
              Deep instruction comprehension, surgical file operations, and intelligent tool selection matrix.
            </p>
          </div>
        </div>

        {/* Tab Controls */}
        <div className={`flex items-center p-1 rounded-xl border ${
          isDark ? "bg-zinc-900 border-zinc-800" : "bg-zinc-100 border-zinc-200"
        }`}>
          <button
            onClick={() => setActiveTab("skills")}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 ${
              activeTab === "skills"
                ? "bg-indigo-600 text-white shadow-xs"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <Wrench className="w-3.5 h-3.5" />
            Skills Catalog ({AGENT_SKILLS_REGISTRY.length})
          </button>
          <button
            onClick={() => setActiveTab("matrix")}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 ${
              activeTab === "matrix"
                ? "bg-indigo-600 text-white shadow-xs"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <Lightbulb className="w-3.5 h-3.5" />
            Which Tool When?
          </button>
          <button
            onClick={() => setActiveTab("playground")}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 ${
              activeTab === "playground"
                ? "bg-indigo-600 text-white shadow-xs"
                : "text-zinc-400 hover:text-zinc-200"
            }`}
          >
            <Play className="w-3.5 h-3.5" />
            Live Operator Playground
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-y-auto p-6">
        {/* Tab 1: Skills Catalog */}
        {activeTab === "skills" && (
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Skills List Column */}
            <div className="lg:col-span-4 space-y-2">
              <span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider block px-1 mb-2">
                Available Agent Skills
              </span>
              {AGENT_SKILLS_REGISTRY.map(skill => {
                const isSelected = skill.id === selectedSkillId;
                return (
                  <button
                    key={skill.id}
                    onClick={() => setSelectedSkillId(skill.id)}
                    className={`w-full text-left p-3.5 rounded-xl border transition-all flex items-start gap-3 ${
                      isSelected
                        ? "bg-indigo-500/10 border-indigo-500/50 shadow-xs"
                        : isDark
                        ? "bg-zinc-900/50 border-zinc-800/70 hover:bg-zinc-900 hover:border-zinc-700"
                        : "bg-zinc-50 border-zinc-200 hover:bg-zinc-100 hover:border-zinc-300"
                    }`}
                  >
                    <div className="mt-0.5 p-2 rounded-lg bg-zinc-800/60 border border-zinc-700/50">
                      {getCategoryIcon(skill.category)}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-bold truncate">{skill.name}</span>
                        <code className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-zinc-800/80 text-indigo-300">
                          {skill.operatorTag}
                        </code>
                      </div>
                      <p className="text-[11px] text-zinc-400 line-clamp-1 mt-1">
                        {skill.whenToUse}
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>

            {/* Skill Detail Column */}
            <div className="lg:col-span-8">
              <div className={`p-6 rounded-2xl border space-y-6 ${
                isDark ? "bg-zinc-900/40 border-zinc-800" : "bg-zinc-50/70 border-zinc-200"
              }`}>
                {/* Header */}
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-center gap-3">
                    <div className="p-2.5 rounded-xl bg-indigo-500/20 border border-indigo-500/30 text-indigo-400">
                      {getCategoryIcon(selectedSkill.category)}
                    </div>
                    <div>
                      <h4 className="text-sm font-bold">{selectedSkill.name}</h4>
                      <code className="text-xs font-mono text-indigo-400">{selectedSkill.operatorTag}</code>
                    </div>
                  </div>

                  <button
                    onClick={() => handleCopy(selectedSkill.syntax, selectedSkill.id)}
                    className="px-2.5 py-1 rounded-lg text-xs font-mono bg-zinc-800 hover:bg-zinc-700 text-zinc-300 flex items-center gap-1.5 transition-colors border border-zinc-700"
                  >
                    {copiedId === selectedSkill.id ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                        <span className="text-emerald-400">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy Syntax</span>
                      </>
                    )}
                  </button>
                </div>

                {/* When to Use & When NOT to use */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5">
                    <div className="flex items-center gap-2 text-emerald-400 text-xs font-bold mb-2">
                      <CheckCircle2 className="w-4 h-4" />
                      When to Use
                    </div>
                    <p className="text-xs text-zinc-300 leading-relaxed">
                      {selectedSkill.whenToUse}
                    </p>
                  </div>

                  <div className="p-4 rounded-xl border border-rose-500/20 bg-rose-500/5">
                    <div className="flex items-center gap-2 text-rose-400 text-xs font-bold mb-2">
                      <ShieldCheck className="w-4 h-4" />
                      When NOT to Use
                    </div>
                    <p className="text-xs text-zinc-300 leading-relaxed">
                      {selectedSkill.whenNotToUse}
                    </p>
                  </div>
                </div>

                {/* Operator Syntax Block */}
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-semibold text-zinc-300 flex items-center gap-1.5">
                      <Code2 className="w-4 h-4 text-indigo-400" />
                      Operator XML Syntax
                    </span>
                  </div>
                  <pre className={`p-4 rounded-xl font-mono text-xs overflow-x-auto border ${
                    isDark ? "bg-zinc-950 border-zinc-800 text-zinc-300" : "bg-white border-zinc-200 text-zinc-800"
                  }`}>
                    {selectedSkill.syntax}
                  </pre>
                </div>

                {/* Best Practices */}
                <div>
                  <h5 className="text-xs font-semibold text-zinc-300 mb-2">Architectural Best Practices</h5>
                  <ul className="space-y-1.5">
                    {selectedSkill.bestPractices.map((bp, i) => (
                      <li key={i} className="text-xs text-zinc-400 flex items-start gap-2">
                        <span className="text-indigo-400 mt-1">•</span>
                        <span>{bp}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Which Tool When? Decision Matrix */}
        {activeTab === "matrix" && (
          <div className="space-y-4">
            <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/30 flex items-start gap-3">
              <Lightbulb className="w-5 h-5 text-indigo-400 mt-0.5 shrink-0" />
              <div className="text-xs leading-relaxed">
                <strong className="text-indigo-300 block mb-1 font-semibold">Autonomous Tool Selection Matrix</strong>
                The AI Agent uses this deterministic decision graph to evaluate incoming user tasks and choose the most surgical, non-destructive file operator without hallucinating or rewriting unchanged codebase files.
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {TOOL_SELECTION_RULES.map((rule, idx) => (
                <div
                  key={idx}
                  className={`p-5 rounded-2xl border space-y-3 ${
                    isDark ? "bg-zinc-900/40 border-zinc-800" : "bg-zinc-50 border-zinc-200"
                  }`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <span className="text-xs font-bold text-zinc-100">{rule.intent}</span>
                    <span className="px-2 py-0.5 rounded font-mono text-[11px] bg-indigo-500/20 text-indigo-300 font-semibold border border-indigo-500/30">
                      {rule.recommendedTool}
                    </span>
                  </div>

                  <p className="text-xs text-zinc-400 leading-relaxed">
                    {rule.rationale}
                  </p>

                  <div className="flex flex-wrap gap-1.5 pt-1">
                    <span className="text-[10px] text-zinc-500 self-center mr-1">Triggers:</span>
                    {rule.triggerKeywords.map((kw, k) => (
                      <span
                        key={k}
                        className="px-2 py-0.5 rounded-md text-[10px] font-mono bg-zinc-800/80 text-zinc-300 border border-zinc-700/50"
                      >
                        {kw}
                      </span>
                    ))}
                  </div>

                  <pre className={`p-3 rounded-lg font-mono text-[11px] overflow-x-auto border ${
                    isDark ? "bg-zinc-950 border-zinc-800 text-zinc-400" : "bg-white border-zinc-200 text-zinc-700"
                  }`}>
                    {rule.operatorTemplate}
                  </pre>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Tab 3: Live Operator Playground */}
        {activeTab === "playground" && (
          <div className="max-w-3xl mx-auto space-y-6">
            <div className={`p-6 rounded-2xl border space-y-5 ${
              isDark ? "bg-zinc-900/40 border-zinc-800" : "bg-zinc-50 border-zinc-200"
            }`}>
              <div>
                <h4 className="text-sm font-bold mb-1">Live Agentic Skill Tester</h4>
                <p className="text-xs text-zinc-400">
                  Select an operation type and target file to simulate the AI agent's exact XML execution format on your live workspace files.
                </p>
              </div>

              {/* Operation Selection */}
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
                {(["read", "edit", "add", "remove", "create"] as const).map(op => (
                  <button
                    key={op}
                    onClick={() => {
                      setSimOperation(op);
                      setSimCustomSnippet("");
                    }}
                    className={`py-2 px-3 rounded-xl text-xs font-semibold uppercase tracking-wider border transition-all flex flex-col items-center gap-1.5 ${
                      simOperation === op
                        ? "bg-indigo-600 text-white border-indigo-500 shadow-xs"
                        : "bg-zinc-800/50 border-zinc-700/60 text-zinc-400 hover:text-zinc-200"
                    }`}
                  >
                    {getCategoryIcon(op)}
                    <span>{op}</span>
                  </button>
                ))}
              </div>

              {/* Target File */}
              {simOperation !== "create" && (
                <div>
                  <label className="text-xs font-semibold text-zinc-300 block mb-1.5">
                    Target Workspace File:
                  </label>
                  <select
                    value={simTargetFile}
                    onChange={(e) => setSimTargetFile(e.target.value)}
                    className={`w-full p-2.5 rounded-xl border text-xs font-mono ${
                      isDark ? "bg-zinc-900 border-zinc-800 text-zinc-200" : "bg-white border-zinc-300 text-zinc-800"
                    }`}
                  >
                    {files.map(f => (
                      <option key={f.path} value={f.path}>
                        {f.path} ({(f.content || "").length} chars)
                      </option>
                    ))}
                  </select>
                </div>
              )}

              {/* Generated XML Snippet */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-xs font-semibold text-zinc-300">
                    Agent XML Operator Snippet:
                  </label>
                  <span className="text-[11px] text-zinc-500 font-mono">Editable</span>
                </div>
                <textarea
                  rows={7}
                  value={simCustomSnippet || generateSimulationSnippet()}
                  onChange={(e) => setSimCustomSnippet(e.target.value)}
                  className={`w-full p-3 rounded-xl border font-mono text-xs ${
                    isDark ? "bg-zinc-950 border-zinc-800 text-emerald-300" : "bg-white border-zinc-300 text-emerald-700"
                  }`}
                />
              </div>

              {/* Execute Button */}
              <div className="flex items-center justify-between pt-2">
                <button
                  onClick={handleRunPlaygroundAction}
                  className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-cyan-600 hover:from-indigo-500 hover:to-cyan-500 text-white font-semibold text-xs flex items-center gap-2 shadow-md transition-all active:scale-95"
                >
                  <Play className="w-4 h-4 fill-white" />
                  Execute Agent Operator on Workspace
                </button>

                {simSuccessMsg && (
                  <span className="text-xs text-emerald-400 font-medium flex items-center gap-1.5 animate-fade-in">
                    <CheckCircle2 className="w-4 h-4" />
                    {simSuccessMsg}
                  </span>
                )}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
