import React, { useState, useMemo } from "react";
import {
  Box,
  Layers,
  Check,
  Copy,
  Download,
  FileCode,
  FolderPlus,
  Play,
  RefreshCw,
  Terminal,
  Settings,
  ShieldCheck,
  Database,
  Cpu,
  Zap,
  Info,
  ExternalLink
} from "lucide-react";
import { VirtualFile } from "../types";

interface DockerDevContainerStudioAgentProps {
  files: VirtualFile[];
  theme?: "light" | "dark" | string;
  onSaveFile: (path: string, content: string) => void;
  onAddLog?: (type: string, message: string) => void;
}

type TabType = "dockerfile" | "compose" | "dockerignore" | "devcontainer" | "cheatsheet";

export const DockerDevContainerStudioAgent: React.FC<DockerDevContainerStudioAgentProps> = ({
  files,
  theme = "dark",
  onSaveFile,
  onAddLog
}) => {
  const isDark = theme !== "light";
  const [activeTab, setActiveTab] = useState<TabType>("dockerfile");
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [savedStatus, setSavedStatus] = useState<string | null>(null);

  // Configuration options
  const [nodeVersion, setNodeVersion] = useState<"22-alpine" | "20-alpine" | "22-slim" | "bun">("22-alpine");
  const [includePostgres, setIncludePostgres] = useState(true);
  const [includeRedis, setIncludeRedis] = useState(false);
  const [appPort, setAppPort] = useState(3000);
  const [multiStage, setMultiStage] = useState(true);
  const [nonRootUser, setNonRootUser] = useState(true);

  // Workspace stack detection
  const detectedStack = useMemo(() => {
    const pkg = files.find(f => f.path === "package.json");
    let hasExpress = false;
    let hasVite = false;
    let hasReact = false;
    let hasTypeScript = false;
    let hasPrisma = false;
    let hasTailwind = false;

    if (pkg && pkg.content) {
      try {
        const json = JSON.parse(pkg.content);
        const deps = { ...(json.dependencies || {}), ...(json.devDependencies || {}) };
        hasExpress = !!deps["express"];
        hasVite = !!deps["vite"];
        hasReact = !!deps["react"];
        hasTypeScript = !!deps["typescript"] || files.some(f => f.path.endsWith(".ts") || f.path.endsWith(".tsx"));
        hasPrisma = !!deps["prisma"] || !!deps["@prisma/client"];
        hasTailwind = !!deps["tailwindcss"] || !!deps["@tailwindcss/vite"];
      } catch {
        // ignore parse error
      }
    }

    const isFullstack = hasExpress && (hasVite || hasReact);

    return {
      type: isFullstack ? "Node.js Fullstack (Express + Vite React)" : hasReact ? "React SPA (Vite)" : hasExpress ? "Express REST API" : "Node.js Application",
      hasExpress,
      hasVite,
      hasReact,
      hasTypeScript,
      hasPrisma,
      hasTailwind
    };
  }, [files]);

  // Generated Dockerfile
  const dockerfileContent = useMemo(() => {
    if (nodeVersion === "bun") {
      return `# ===================================================
# Dockerfile: High-Performance Bun Container
# Generated by Remix Studio Docker Agent
# ===================================================
FROM oven/bun:1.1-alpine AS base
WORKDIR /app

# Stage 1: Dependencies Cache
FROM base AS deps
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# Stage 2: Application Build
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build || echo "No custom build step required"

# Stage 3: Production Runner
FROM base AS runner
ENV NODE_ENV=production
ENV PORT=${appPort}
${nonRootUser ? "USER bun" : ""}
COPY --from=builder --chown=bun:bun /app ./

EXPOSE ${appPort}
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${appPort}/api/health || exit 1

CMD ["bun", "run", "start"]
`;
    }

    if (!multiStage) {
      return `# ===================================================
# Dockerfile: Single-Stage Node.js Development
# Generated by Remix Studio Docker Agent
# ===================================================
FROM node:${nodeVersion}
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy application sources
COPY . .

# Build assets
RUN npm run build || true

ENV NODE_ENV=production
ENV PORT=${appPort}
${nonRootUser ? "USER node" : ""}

EXPOSE ${appPort}
CMD ["npm", "start"]
`;
    }

    return `# ===================================================
# Dockerfile: Production Multi-Stage Hardened Container
# Optimized for minimum image size & layer caching
# ===================================================

# ----------------- Stage 1: Dependencies -----------------
FROM node:${nodeVersion} AS deps
WORKDIR /app
RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json* ./
RUN npm ci --include=dev

# ----------------- Stage 2: Application Builder ----------
FROM node:${nodeVersion} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NODE_ENV=production
RUN npm run build

# ----------------- Stage 3: Production Runner ------------
FROM node:${nodeVersion} AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=${appPort}

${nonRootUser ? `# Security: run as non-privileged unprivileged user
USER node` : ""}

# Copy built application and required production packages
COPY --from=builder --chown=node:node /app/package.json ./
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/dist ./dist
COPY --from=builder --chown=node:node /app/server.ts ./server.ts 2>/dev/null || true
COPY --from=builder --chown=node:node /app/dist/server.cjs ./dist/server.cjs 2>/dev/null || true

EXPOSE ${appPort}

# Built-in Container Healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget -qO- http://localhost:${appPort}/api/health || exit 1

CMD ["npm", "start"]
`;
  }, [nodeVersion, multiStage, nonRootUser, appPort]);

  // Generated docker-compose.yml
  const composeContent = useMemo(() => {
    let services = `version: "3.8"

services:
  # Main Web Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remix_studio_app
    restart: unless-stopped
    ports:
      - "${appPort}:${appPort}"
    environment:
      - PORT=${appPort}
      - NODE_ENV=production
      ${includePostgres ? `- DATABASE_URL=postgres://app_user:app_secure_password@postgres:5432/app_db` : ""}
      ${includeRedis ? `- REDIS_URL=redis://redis:6379` : ""}
    ${includePostgres || includeRedis ? `depends_on:` : ""}
    ${includePostgres ? `  postgres:\n        condition: service_healthy` : ""}
    ${includeRedis ? `  redis:\n        condition: service_started` : ""}
    networks:
      - app-network
`;

    if (includePostgres) {
      services += `
  # PostgreSQL Relational Database Service
  postgres:
    image: postgres:16-alpine
    container_name: remix_studio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_secure_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
`;
    }

    if (includeRedis) {
      services += `
  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: remix_studio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
`;
    }

    services += `
networks:
  app-network:
    driver: bridge

volumes:
`;
    if (includePostgres) services += `  postgres_data:\n`;
    if (includeRedis) services += `  redis_data:\n`;

    return services;
  }, [appPort, includePostgres, includeRedis]);

  // Generated .dockerignore
  const dockerignoreContent = `# ===================================================
# .dockerignore: Ignore bulky, local, and secret files
# ===================================================
node_modules
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# Git repository
.git
.gitignore

# Environment & local credentials
.env
.env.local
.env.*.local
*.pem
*.key

# Build outputs
dist
build
.next
.output
.cache

# IDE and OS artifacts
.vscode
.idea
*.suo
*.ntvs*
*.njsproj
.DS_Store
Thumbs.db

# Test coverage
coverage
.nyc_output
`;

  // Generated .devcontainer/devcontainer.json
  const devcontainerContent = `{
  "name": "Remix Studio Development Container",
  "dockerComposeFile": "../docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/app",
  "customizations": {
    "vscode": {
      "settings": {
        "terminal.integrated.defaultProfile.linux": "bash",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "esbenp.prettier-vscode"
      },
      "extensions": [
        "dbaeumer.vscode-eslint",
        "esbenp.prettier-vscode",
        "bradlc.vscode-tailwindcss",
        "ms-azuretools.vscode-docker"
      ]
    }
  },
  "forwardPorts": [${appPort}${includePostgres ? ", 5432" : ""}${includeRedis ? ", 6379" : ""}],
  "postCreateCommand": "npm install",
  "remoteUser": "node"
}
`;

  // Get active file content
  const activeContent = useMemo(() => {
    switch (activeTab) {
      case "dockerfile":
        return dockerfileContent;
      case "compose":
        return composeContent;
      case "dockerignore":
        return dockerignoreContent;
      case "devcontainer":
        return devcontainerContent;
      default:
        return "";
    }
  }, [activeTab, dockerfileContent, composeContent, dockerignoreContent, devcontainerContent]);

  const activeFilename = useMemo(() => {
    switch (activeTab) {
      case "dockerfile":
        return "Dockerfile";
      case "compose":
        return "docker-compose.yml";
      case "dockerignore":
        return ".dockerignore";
      case "devcontainer":
        return ".devcontainer/devcontainer.json";
      default:
        return "";
    }
  }, [activeTab]);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleSaveActiveToWorkspace = () => {
    if (!activeFilename || !activeContent) return;
    onSaveFile(activeFilename, activeContent);
    setSavedStatus(`Saved ${activeFilename}`);
    if (onAddLog) onAddLog("create", `Saved ${activeFilename} to workspace`);
    setTimeout(() => setSavedStatus(null), 3000);
  };

  const handleSaveAllToWorkspace = () => {
    onSaveFile("Dockerfile", dockerfileContent);
    onSaveFile("docker-compose.yml", composeContent);
    onSaveFile(".dockerignore", dockerignoreContent);
    onSaveFile(".devcontainer/devcontainer.json", devcontainerContent);
    setSavedStatus("Saved all 4 Docker & Container files!");
    if (onAddLog) onAddLog("create", "Generated and saved Dockerfile, docker-compose.yml, .dockerignore, and devcontainer.json");
    setTimeout(() => setSavedStatus(null), 3500);
  };

  return (
    <div className={`w-full h-full flex flex-col overflow-hidden ${isDark ? "bg-[#101014] text-white" : "bg-slate-50 text-slate-900"}`}>
      {/* Studio Header */}
      <div className={`px-5 py-3.5 border-b flex items-center justify-between shrink-0 ${isDark ? "border-zinc-800 bg-[#141418]" : "border-slate-200 bg-white"}`}>
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-sky-600 text-white shadow-md">
            <Box className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-base font-bold tracking-tight">Docker & Dev Container Architect</h1>
              <span className="text-[10px] px-2 py-0.5 rounded-full font-mono font-bold bg-sky-500/20 text-sky-400 border border-sky-500/30">
                Multi-Stage Ready
              </span>
            </div>
            <p className={`text-xs ${isDark ? "text-zinc-400" : "text-slate-500"}`}>
              Production Dockerfiles, multi-service docker-compose, and VS Code devcontainer presets tailored to your workspace.
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          {savedStatus && (
            <span className="text-xs font-semibold text-emerald-400 flex items-center gap-1 animate-in fade-in">
              <Check className="w-4 h-4" /> {savedStatus}
            </span>
          )}

          <button
            onClick={handleSaveActiveToWorkspace}
            className={`px-3 py-1.5 rounded-lg border text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer ${
              isDark ? "border-zinc-700 bg-zinc-800 text-zinc-200 hover:bg-zinc-700" : "border-slate-300 bg-slate-100 text-slate-800 hover:bg-slate-200"
            }`}
            title={`Write ${activeFilename} into workspace files`}
          >
            <FolderPlus className="w-3.5 h-3.5 text-sky-400" />
            <span>Save Active File</span>
          </button>

          <button
            onClick={handleSaveAllToWorkspace}
            className="px-3.5 py-1.5 rounded-lg bg-sky-600 hover:bg-sky-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-md shadow-sky-600/20 transition-all cursor-pointer"
            title="Write Dockerfile, docker-compose.yml, .dockerignore, and devcontainer.json to project"
          >
            <Layers className="w-3.5 h-3.5" />
            <span>Save All to Project</span>
          </button>
        </div>
      </div>

      {/* Main Grid: Settings Sidebar & Editor Canvas */}
      <div className="flex-1 flex min-h-0 overflow-hidden">
        {/* Left: Configuration & Detection Panel */}
        <div className={`w-72 lg:w-80 border-r flex flex-col p-4 space-y-5 overflow-y-auto shrink-0 ${
          isDark ? "border-zinc-800 bg-[#121216]" : "border-slate-200 bg-white"
        }`}>
          {/* Workspace Stack Detection Badge */}
          <div className={`p-3 rounded-xl border ${isDark ? "border-zinc-800 bg-zinc-900/60" : "border-slate-200 bg-slate-50"}`}>
            <div className="flex items-center gap-2 mb-1.5">
              <Cpu className="w-4 h-4 text-sky-400" />
              <span className="text-xs font-bold uppercase tracking-wider text-sky-400">Detected Workspace</span>
            </div>
            <p className="text-xs font-semibold">{detectedStack.type}</p>
            <div className="flex flex-wrap gap-1.5 mt-2">
              {detectedStack.hasVite && <span className="px-1.5 py-0.5 rounded text-[10px] bg-purple-500/20 text-purple-300 font-mono">Vite</span>}
              {detectedStack.hasReact && <span className="px-1.5 py-0.5 rounded text-[10px] bg-cyan-500/20 text-cyan-300 font-mono">React 19</span>}
              {detectedStack.hasExpress && <span className="px-1.5 py-0.5 rounded text-[10px] bg-emerald-500/20 text-emerald-300 font-mono">Express</span>}
              {detectedStack.hasTypeScript && <span className="px-1.5 py-0.5 rounded text-[10px] bg-blue-500/20 text-blue-300 font-mono">TypeScript</span>}
              {detectedStack.hasTailwind && <span className="px-1.5 py-0.5 rounded text-[10px] bg-teal-500/20 text-teal-300 font-mono">Tailwind v4</span>}
            </div>
          </div>

          {/* Configuration Controls */}
          <div className="space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400">Container Options</h3>

            {/* Base Image Engine */}
            <div>
              <label className="text-xs font-medium block mb-1">Base Runtime Engine</label>
              <select
                value={nodeVersion}
                onChange={(e) => setNodeVersion(e.target.value as any)}
                className={`w-full text-xs px-2.5 py-1.5 rounded-lg border focus:outline-none cursor-pointer ${
                  isDark ? "bg-zinc-900 border-zinc-700 text-white" : "bg-slate-50 border-slate-300 text-slate-900"
                }`}
              >
                <option value="22-alpine">Node.js 22 LTS (Alpine Linux - Ultralight)</option>
                <option value="20-alpine">Node.js 20 LTS (Alpine Linux)</option>
                <option value="22-slim">Node.js 22 Slim (Debian glibc)</option>
                <option value="bun">Bun 1.1 (High-Performance Engine)</option>
              </select>
            </div>

            {/* Exposed Port */}
            <div>
              <label className="text-xs font-medium block mb-1">Application Port</label>
              <input
                type="number"
                value={appPort}
                onChange={(e) => setAppPort(Number(e.target.value) || 3000)}
                className={`w-full text-xs px-2.5 py-1.5 rounded-lg border focus:outline-none ${
                  isDark ? "bg-zinc-900 border-zinc-700 text-white" : "bg-slate-50 border-slate-300 text-slate-900"
                }`}
              />
            </div>

            {/* Compose Services */}
            <div className="space-y-2 pt-2 border-t border-zinc-800">
              <label className="text-xs font-semibold block text-zinc-400">Additional Services (compose)</label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={includePostgres}
                  onChange={(e) => setIncludePostgres(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <Database className="w-3.5 h-3.5 text-blue-400" />
                <span>PostgreSQL 16 (Port 5432)</span>
              </label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={includeRedis}
                  onChange={(e) => setIncludeRedis(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <Zap className="w-3.5 h-3.5 text-rose-400" />
                <span>Redis 7 Cache (Port 6379)</span>
              </label>
            </div>

            {/* Hardening Options */}
            <div className="space-y-2 pt-2 border-t border-zinc-800">
              <label className="text-xs font-semibold block text-zinc-400">Hardening & Optimization</label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={multiStage}
                  onChange={(e) => setMultiStage(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <Layers className="w-3.5 h-3.5 text-sky-400" />
                <span>Multi-Stage Layer Caching</span>
              </label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={nonRootUser}
                  onChange={(e) => setNonRootUser(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span>Non-Root User (<code className="font-mono">USER node</code>)</span>
              </label>
            </div>
          </div>
        </div>

        {/* Right: File Preview & Editor */}
        <div className="flex-1 flex flex-col min-w-0 min-h-0 overflow-hidden">
          {/* File Tabs Bar */}
          <div className={`px-4 pt-2 border-b flex items-center justify-between shrink-0 ${
            isDark ? "border-zinc-800 bg-[#141418]" : "border-slate-200 bg-slate-100"
          }`}>
            <div className="flex items-center gap-1.5 overflow-x-auto scrollbar-none">
              <button
                onClick={() => setActiveTab("dockerfile")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "dockerfile"
                    ? (isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs")
                    : (isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900")
                }`}
              >
                <FileCode className="w-3.5 h-3.5" />
                <span>Dockerfile</span>
              </button>

              <button
                onClick={() => setActiveTab("compose")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "compose"
                    ? (isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs")
                    : (isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900")
                }`}
              >
                <Layers className="w-3.5 h-3.5" />
                <span>docker-compose.yml</span>
              </button>

              <button
                onClick={() => setActiveTab("dockerignore")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "dockerignore"
                    ? (isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs")
                    : (isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900")
                }`}
              >
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>.dockerignore</span>
              </button>

              <button
                onClick={() => setActiveTab("devcontainer")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "devcontainer"
                    ? (isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs")
                    : (isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900")
                }`}
              >
                <Settings className="w-3.5 h-3.5" />
                <span>devcontainer.json</span>
              </button>

              <button
                onClick={() => setActiveTab("cheatsheet")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "cheatsheet"
                    ? (isDark ? "bg-[#101014] text-amber-400 border-t-2 border-amber-500" : "bg-white text-amber-600 border-t-2 border-amber-600 shadow-xs")
                    : (isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900")
                }`}
              >
                <Terminal className="w-3.5 h-3.5" />
                <span>CLI Cheat Sheet</span>
              </button>
            </div>

            {/* Copy button */}
            {activeTab !== "cheatsheet" && (
              <button
                onClick={() => copyToClipboard(activeContent, "active")}
                className={`flex items-center gap-1 px-2.5 py-1 mb-1 rounded-md text-xs font-semibold border transition-colors cursor-pointer ${
                  isDark ? "border-zinc-700 bg-zinc-800 text-zinc-300 hover:text-white" : "border-slate-300 bg-white text-slate-700 hover:bg-slate-50"
                }`}
              >
                {copiedKey === "active" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === "active" ? "Copied!" : "Copy"}</span>
              </button>
            )}
          </div>

          {/* Content Pane */}
          <div className="flex-1 overflow-auto p-4 font-mono text-xs">
            {activeTab === "cheatsheet" ? (
              <div className="space-y-4 max-w-3xl font-sans">
                <div className={`p-4 rounded-xl border ${isDark ? "border-zinc-800 bg-[#121216]" : "border-slate-200 bg-white"}`}>
                  <h4 className="font-bold text-sm text-sky-400 mb-2 flex items-center gap-2">
                    <Terminal className="w-4 h-4" /> Docker CLI Production Workflow
                  </h4>
                  <p className="text-xs text-zinc-400 mb-4">
                    Run these commands in your project terminal to build, run, and manage your containers.
                  </p>

                  <div className="space-y-3 font-mono text-xs">
                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">1. Build Docker image with tag:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker build -t my-app:latest .</code>
                        <button onClick={() => copyToClipboard("docker build -t my-app:latest .", "c1")} className="p-1 hover:text-sky-400">
                          {copiedKey === "c1" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">2. Run standalone container on port {appPort}:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker run -d -p {appPort}:{appPort} --name my-running-app my-app:latest</code>
                        <button onClick={() => copyToClipboard(`docker run -d -p ${appPort}:${appPort} --name my-running-app my-app:latest`, "c2")} className="p-1 hover:text-sky-400">
                          {copiedKey === "c2" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">3. Start all services with Docker Compose:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker-compose up -d --build</code>
                        <button onClick={() => copyToClipboard("docker-compose up -d --build", "c3")} className="p-1 hover:text-sky-400">
                          {copiedKey === "c3" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">4. Stream real-time logs:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker-compose logs -f app</code>
                        <button onClick={() => copyToClipboard("docker-compose logs -f app", "c4")} className="p-1 hover:text-sky-400">
                          {copiedKey === "c4" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">5. Open interactive shell inside running container:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker-compose exec app sh</code>
                        <button onClick={() => copyToClipboard("docker-compose exec app sh", "c5")} className="p-1 hover:text-sky-400">
                          {copiedKey === "c5" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <pre className={`p-4 rounded-xl border leading-relaxed overflow-x-auto whitespace-pre ${
                isDark ? "bg-[#0c0c0e] border-zinc-800 text-zinc-200" : "bg-white border-slate-200 text-slate-800"
              }`}>
                <code>{activeContent}</code>
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
export default DockerDevContainerStudioAgent;
