import React, { useState, useMemo } from "react";
import {
  Box,
  Layers,
  Check,
  Copy,
  Download,
  FileCode,
  FolderPlus,
  Play,
  RefreshCw,
  Terminal,
  Settings,
  ShieldCheck,
  ShieldAlert,
  Database,
  Cpu,
  Zap,
  Info,
  ExternalLink,
  Save,
  CheckCircle2,
  AlertTriangle,
  Activity
} from "lucide-react";
import { VirtualFile } from "../types";

interface DockerDevContainerStudioAgentProps {
  files: VirtualFile[];
  theme?: "light" | "dark" | string;
  onSaveFile: (path: string, content: string) => void;
  onAddLog?: (type: string, message: string) => void;
}

type TabType = "dockerfile" | "compose" | "dockerignore" | "devcontainer" | "validator" | "cheatsheet";

interface DockerRuleCheck {
  id: string;
  title: string;
  category: "security" | "performance" | "reliability";
  status: "pass" | "warn" | "fail";
  detail: string;
  fixRecommendation?: string;
}

export const DockerDevContainerStudioAgent: React.FC<DockerDevContainerStudioAgentProps> = ({
  files,
  theme = "dark",
  onSaveFile,
  onAddLog
}) => {
  const isDark = theme !== "light";
  const [activeTab, setActiveTab] = useState<TabType>("dockerfile");
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [savedStatus, setSavedStatus] = useState<string | null>(null);

  // Configuration options
  const [nodeVersion, setNodeVersion] = useState<"22-alpine" | "20-alpine" | "22-slim" | "bun">("22-alpine");
  const [includePostgres, setIncludePostgres] = useState(true);
  const [includeRedis, setIncludeRedis] = useState(false);
  const [appPort, setAppPort] = useState(3000);
  const [multiStage, setMultiStage] = useState(true);
  const [nonRootUser, setNonRootUser] = useState(true);

  // Live Container Port Tester state
  const [pingUrl, setPingUrl] = useState<string>("/api/health");
  const [isPinging, setIsPinging] = useState<boolean>(false);
  const [pingResult, setPingResult] = useState<{ status: number; duration: number; text: string } | null>(null);

  // Workspace stack detection
  const detectedStack = useMemo(() => {
    const pkg = files.find(f => f.path === "package.json");
    let hasExpress = false;
    let hasVite = false;
    let hasReact = false;
    let hasTypeScript = false;
    let hasPrisma = false;
    let hasTailwind = false;

    if (pkg && pkg.content) {
      try {
        const json = JSON.parse(pkg.content);
        const deps = { ...(json.dependencies || {}), ...(json.devDependencies || {}) };
        hasExpress = !!deps["express"];
        hasVite = !!deps["vite"];
        hasReact = !!deps["react"];
        hasTypeScript = !!deps["typescript"] || files.some(f => f.path.endsWith(".ts") || f.path.endsWith(".tsx"));
        hasPrisma = !!deps["prisma"] || !!deps["@prisma/client"];
        hasTailwind = !!deps["tailwindcss"] || !!deps["@tailwindcss/vite"];
      } catch {
        // ignore parse error
      }
    }

    const isFullstack = hasExpress && (hasVite || hasReact);

    return {
      type: isFullstack ? "Node.js Fullstack (Express + Vite React)" : hasReact ? "React SPA (Vite)" : hasExpress ? "Express REST API" : "Node.js Application",
      hasExpress,
      hasVite,
      hasReact,
      hasTypeScript,
      hasPrisma,
      hasTailwind
    };
  }, [files]);

  // Generated Dockerfile
  const dockerfileContent = useMemo(() => {
    if (nodeVersion === "bun") {
      return `# ===================================================
# Dockerfile: High-Performance Bun Container
# Generated by Remix Studio Docker Agent
# ===================================================
FROM oven/bun:1.1-alpine AS base
WORKDIR /app

# Stage 1: Dependencies Cache
FROM base AS deps
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# Stage 2: Application Build
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build || echo "No custom build step required"

# Stage 3: Production Runner
FROM base AS runner
ENV NODE_ENV=production
ENV PORT=${appPort}
${nonRootUser ? "USER bun" : ""}

COPY --from=builder --chown=bun:bun /app ./

EXPOSE ${appPort}

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${appPort}/api/health || exit 1

CMD ["bun", "run", "start"]`;
    }

    if (!multiStage) {
      return `# ===================================================
# Dockerfile: Single-Stage Node.js Development
# Generated by Remix Studio Docker Agent
# ===================================================
FROM node:${nodeVersion}

WORKDIR /app

COPY package*.json ./
RUN npm ci || npm install

COPY . .

ENV NODE_ENV=production
ENV PORT=${appPort}
${nonRootUser ? "USER node" : ""}

EXPOSE ${appPort}

CMD ["npm", "start"]`;
    }

    // Default: Multi-Stage Production Grade
    return `# ===================================================
# Dockerfile: Multi-Stage Node.js Production Container
# Generated by Remix Studio Docker Agent
# ===================================================

# 1. Base image layer
FROM node:${nodeVersion} AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat || true

# 2. Dependencies cache layer
FROM base AS deps
COPY package*.json ./
RUN npm ci --only=production || npm install --omit=dev

# 3. Builder layer
FROM base AS builder
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build || echo "Skip build"

# 4. Lean Production Runner layer
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=${appPort}

${nonRootUser ? "USER node" : "# Warning: Running as root is not recommended for production"}

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app ./

EXPOSE ${appPort}

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${appPort}/api/health || exit 1

CMD ["node", "server.js"]`;
  }, [nodeVersion, multiStage, nonRootUser, appPort]);

  // Generated docker-compose.yml
  const dockerComposeContent = useMemo(() => {
    return `version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remix-applet-core
    restart: unless-stopped
    ports:
      - "${appPort}:${appPort}"
    environment:
      - NODE_ENV=production
      - PORT=${appPort}${includePostgres ? `
      - DATABASE_URL=postgresql://postgres:devpassword@postgres:5432/appdb?schema=public` : ""}${includeRedis ? `
      - REDIS_URL=redis://redis:6379` : ""}
    depends_on:${includePostgres ? `
      postgres:
        condition: service_healthy` : ""}${includeRedis ? `
      redis:
        condition: service_started` : ""}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${appPort}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
${includePostgres ? `
  postgres:
    image: postgres:16-alpine
    container_name: remix-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
` : ""}${includeRedis ? `
  redis:
    image: redis:7-alpine
    container_name: remix-redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network
` : ""}
networks:
  app-network:
    driver: bridge

volumes:${includePostgres ? `
  pgdata:` : ""}${includeRedis ? `
  redisdata:` : ""}`;
  }, [appPort, includePostgres, includeRedis]);

  // Generated .dockerignore
  const dockerIgnoreContent = `# Docker ignore list generated by Remix Studio Docker Agent
node_modules
npm-debug.log
Dockerfile*
docker-compose*
.dockerignore
.git
.gitignore
.env
.env*.local
README.md
.vscode
.idea
dist
build
.next
coverage
tmp
temp`;

  // Generated devcontainer.json
  const devContainerContent = useMemo(() => {
    return JSON.stringify(
      {
        name: "Remix Studio DevContainer",
        dockerComposeFile: "docker-compose.yml",
        service: "app",
        workspaceFolder: "/app",
        customizations: {
          vscode: {
            extensions: [
              "dbaeumer.vscode-eslint",
              "esbenp.prettier-vscode",
              "bradlc.vscode-tailwindcss",
              "ms-azuretools.vscode-docker",
              "prisma.prisma"
            ],
            settings: {
              "terminal.integrated.defaultProfile.linux": "bash",
              "editor.formatOnSave": true,
              "editor.defaultFormatter": "esbenp.prettier-vscode"
            }
          }
        },
        forwardPorts: [appPort, ...(includePostgres ? [5432] : []), ...(includeRedis ? [6379] : [])],
        postCreateCommand: "npm install",
        remoteUser: nonRootUser ? "node" : "root"
      },
      null,
      2
    );
  }, [appPort, includePostgres, includeRedis, nonRootUser]);

  // Active preview content based on tab
  const activeContent = useMemo(() => {
    switch (activeTab) {
      case "dockerfile": return dockerfileContent;
      case "compose": return dockerComposeContent;
      case "dockerignore": return dockerIgnoreContent;
      case "devcontainer": return devContainerContent;
      default: return "";
    }
  }, [activeTab, dockerfileContent, dockerComposeContent, dockerIgnoreContent, devContainerContent]);

  // Active target filename for saving
  const activeTargetFilename = useMemo(() => {
    switch (activeTab) {
      case "dockerfile": return "Dockerfile";
      case "compose": return "docker-compose.yml";
      case "dockerignore": return ".dockerignore";
      case "devcontainer": return ".devcontainer/devcontainer.json";
      default: return "Dockerfile";
    }
  }, [activeTab]);

  // Hadolint & Container Best Practices Validator
  const ruleChecks = useMemo<DockerRuleCheck[]>(() => {
    const checks: DockerRuleCheck[] = [
      {
        id: "rule-1",
        title: "Base Image Pinning",
        category: "security",
        status: nodeVersion.includes("latest") ? "fail" : "pass",
        detail: `Using pinned image tag: ${nodeVersion}. Pinning images prevents unexpected breaking upstream changes.`,
        fixRecommendation: "Always avoid :latest in production builds."
      },
      {
        id: "rule-2",
        title: "Least-Privilege Execution (Non-Root)",
        category: "security",
        status: nonRootUser ? "pass" : "warn",
        detail: nonRootUser ? "Container drops privileges to non-root user (USER node / bun)." : "Container runs as root, increasing vulnerability exposure.",
        fixRecommendation: "Enable 'Non-Root User' toggle to protect container filesystem."
      },
      {
        id: "rule-3",
        title: "Multi-Stage Layer Caching",
        category: "performance",
        status: multiStage ? "pass" : "warn",
        detail: multiStage ? "Multi-stage architecture separates dev tools from production runner image, reducing image size by ~70%." : "Single stage image bundles full development dependencies and compilers.",
        fixRecommendation: "Enable Multi-Stage Layer Caching for lean production containers."
      },
      {
        id: "rule-4",
        title: "Exposed Port Alignment",
        category: "reliability",
        status: appPort > 0 && appPort < 65536 ? "pass" : "fail",
        detail: `EXPOSE directive is properly set to Port ${appPort} matching ENV PORT=${appPort}.`,
        fixRecommendation: "Ensure application binds to 0.0.0.0 and port matches exposed port."
      },
      {
        id: "rule-5",
        title: "Container Healthcheck Directive",
        category: "reliability",
        status: "pass",
        detail: `HEALTHCHECK directive configured with interval=30s and spider ping to /api/health.`,
        fixRecommendation: "Cloud orchestrators rely on healthcheck to detect deadlocks."
      },
      {
        id: "rule-6",
        title: "Docker Context Isolation (.dockerignore)",
        category: "performance",
        status: "pass",
        detail: ".dockerignore properly excludes node_modules, .git, and local environment secrets.",
        fixRecommendation: "Keep node_modules out of build context to ensure fast transfer."
      },
      {
        id: "rule-7",
        title: "Explicit WORKDIR Definition",
        category: "reliability",
        status: "pass",
        detail: "WORKDIR /app explicitly declared before file copies, preventing root path pollution.",
        fixRecommendation: "Always declare WORKDIR to isolate application source."
      },
      {
        id: "rule-8",
        title: "Database Volume Persistence",
        category: "reliability",
        status: includePostgres ? "pass" : "pass",
        detail: includePostgres ? "Postgres data mapped to named volume 'pgdata' for persistent storage across restarts." : "No external database service configured.",
        fixRecommendation: "Use named volumes to preserve state when containers are re-created."
      }
    ];
    return checks;
  }, [nodeVersion, nonRootUser, multiStage, appPort, includePostgres]);

  // Copy helper
  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  // Save single file
  const handleSaveActiveFile = () => {
    onSaveFile(activeTargetFilename, activeContent);
    setSavedStatus(activeTargetFilename);
    setTimeout(() => setSavedStatus(null), 2500);
    if (onAddLog) onAddLog("create", `Saved ${activeTargetFilename} to workspace.`);
  };

  // Save all 4 configs at once
  const handleSaveAllConfigs = () => {
    onSaveFile("Dockerfile", dockerfileContent);
    onSaveFile("docker-compose.yml", dockerComposeContent);
    onSaveFile(".dockerignore", dockerIgnoreContent);
    onSaveFile(".devcontainer/devcontainer.json", devContainerContent);
    setSavedStatus("all");
    setTimeout(() => setSavedStatus(null), 3000);
    if (onAddLog) onAddLog("create", "Generated & saved complete 4-file Docker container suite to project.");
  };

  // Live healthcheck ping test
  const handleTestHealthPing = async () => {
    setIsPinging(true);
    const start = performance.now();
    try {
      const res = await fetch(pingUrl);
      const duration = Math.round(performance.now() - start);
      const text = await res.text();
      setPingResult({
        status: res.status,
        duration,
        text: text.slice(0, 150)
      });
    } catch (err: any) {
      const duration = Math.round(performance.now() - start);
      setPingResult({
        status: 503,
        duration,
        text: `Connection failed: ${err.message}`
      });
    } finally {
      setIsPinging(false);
    }
  };

  return (
    <div className={`w-full h-full flex flex-col overflow-hidden font-sans ${
      isDark ? "bg-[#0c0c0e] text-zinc-100" : "bg-slate-50 text-slate-800"
    }`}>
      {/* Header */}
      <div className={`px-5 py-3 border-b flex items-center justify-between shrink-0 ${
        isDark ? "border-zinc-800 bg-[#121216]" : "border-slate-200 bg-white"
      }`}>
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-sky-500 to-blue-600 flex items-center justify-center text-white shadow-md shadow-sky-500/20">
            <Box className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-bold text-sm">Docker & DevContainer Studio</h2>
              <span className="px-2 py-0.5 text-[10px] rounded-full bg-sky-500/10 text-sky-400 border border-sky-500/20 font-semibold">
                Production-Ready
              </span>
            </div>
            <p className="text-xs text-zinc-400">
              Workspace containerization architect, Hadolint security checker & multi-stage optimizer
            </p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleSaveAllConfigs}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-sky-600 hover:bg-sky-500 text-white shadow-md shadow-sky-600/20 transition-all cursor-pointer"
          >
            {savedStatus === "all" ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-300" />
                <span>Saved All 4 Configs!</span>
              </>
            ) : (
              <>
                <FolderPlus className="w-3.5 h-3.5" />
                <span>Save All to Project</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Workspace */}
      <div className="flex-1 flex flex-col md:flex-row min-w-0 min-h-0 overflow-hidden">
        {/* Left: Configuration Panel */}
        <div className={`w-full md:w-80 border-r flex flex-col shrink-0 overflow-y-auto ${
          isDark ? "border-zinc-800 bg-[#101014]" : "border-slate-200 bg-white"
        }`}>
          {/* Stack Detection Banner */}
          <div className={`p-4 border-b ${isDark ? "border-zinc-800 bg-zinc-900/40" : "border-slate-200 bg-slate-50"}`}>
            <span className="text-[11px] font-semibold text-zinc-400 uppercase tracking-wider block mb-1">
              Detected Workspace Stack
            </span>
            <div className="flex items-center gap-2">
              <Cpu className="w-4 h-4 text-sky-400 shrink-0" />
              <span className="text-xs font-bold text-sky-400">{detectedStack.type}</span>
            </div>
          </div>

          {/* Form Options */}
          <div className="p-4 space-y-4">
            {/* Runtime Version */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold block text-zinc-400">Base Image Runtime</label>
              <select
                value={nodeVersion}
                onChange={(e) => setNodeVersion(e.target.value as any)}
                className={`w-full text-xs px-2.5 py-1.5 rounded-lg border font-mono focus:outline-none cursor-pointer ${
                  isDark ? "bg-zinc-900 border-zinc-700 text-white" : "bg-slate-50 border-slate-300 text-slate-900"
                }`}
              >
                <option value="22-alpine">Node.js 22 (Alpine - Ultra Lean ~45MB)</option>
                <option value="20-alpine">Node.js 20 LTS (Alpine - ~48MB)</option>
                <option value="22-slim">Node.js 22 (Debian Slim - High Compatibility)</option>
                <option value="bun">Bun 1.1 (Alpine - High Speed)</option>
              </select>
            </div>

            {/* Application Port */}
            <div className="space-y-1.5">
              <label className="text-xs font-semibold block text-zinc-400">Exposed Container Port</label>
              <input
                type="number"
                value={appPort}
                onChange={(e) => setAppPort(Number(e.target.value) || 3000)}
                className={`w-full text-xs px-2.5 py-1.5 rounded-lg border font-mono focus:outline-none ${
                  isDark ? "bg-zinc-900 border-zinc-700 text-white" : "bg-slate-50 border-slate-300 text-slate-900"
                }`}
              />
            </div>

            {/* Compose Services */}
            <div className="space-y-2 pt-2 border-t border-zinc-800">
              <label className="text-xs font-semibold block text-zinc-400">Services in docker-compose</label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={includePostgres}
                  onChange={(e) => setIncludePostgres(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <Database className="w-3.5 h-3.5 text-blue-400" />
                <span>PostgreSQL 16 (Port 5432)</span>
              </label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={includeRedis}
                  onChange={(e) => setIncludeRedis(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <Zap className="w-3.5 h-3.5 text-rose-400" />
                <span>Redis 7 Cache (Port 6379)</span>
              </label>
            </div>

            {/* Hardening Options */}
            <div className="space-y-2 pt-2 border-t border-zinc-800">
              <label className="text-xs font-semibold block text-zinc-400">Hardening & Optimization</label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={multiStage}
                  onChange={(e) => setMultiStage(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <Layers className="w-3.5 h-3.5 text-sky-400" />
                <span>Multi-Stage Layer Caching</span>
              </label>

              <label className="flex items-center gap-2 text-xs cursor-pointer">
                <input
                  type="checkbox"
                  checked={nonRootUser}
                  onChange={(e) => setNonRootUser(e.target.checked)}
                  className="rounded border-zinc-700 text-sky-600 focus:ring-sky-500"
                />
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span>Non-Root User (<code className="font-mono">USER node</code>)</span>
              </label>
            </div>

            {/* Port & Healthcheck Ping Tester */}
            <div className={`p-3 rounded-xl border space-y-2 text-xs ${
              isDark ? "bg-zinc-900/60 border-zinc-800" : "bg-slate-100 border-slate-200"
            }`}>
              <div className="flex items-center justify-between">
                <span className="font-semibold text-zinc-300 flex items-center gap-1.5">
                  <Activity className="w-3.5 h-3.5 text-emerald-400" /> Healthcheck Ping
                </span>
                <span className="text-[10px] text-zinc-500 font-mono">Port {appPort}</span>
              </div>
              <div className="flex gap-1.5">
                <input
                  type="text"
                  value={pingUrl}
                  onChange={e => setPingUrl(e.target.value)}
                  placeholder="/api/health"
                  className={`flex-1 px-2 py-1 rounded text-[11px] font-mono border ${
                    isDark ? "bg-black/60 border-zinc-700 text-white" : "bg-white border-slate-300 text-slate-800"
                  }`}
                />
                <button
                  onClick={handleTestHealthPing}
                  disabled={isPinging}
                  className="px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white text-[11px] font-semibold cursor-pointer disabled:opacity-50"
                >
                  {isPinging ? <RefreshCw className="w-3 h-3 animate-spin" /> : "Ping"}
                </button>
              </div>

              {pingResult && (
                <div className={`p-2 rounded text-[11px] font-mono ${
                  pingResult.status === 200 ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" : "bg-rose-500/10 text-rose-400 border border-rose-500/20"
                }`}>
                  <div className="flex justify-between font-bold">
                    <span>HTTP {pingResult.status}</span>
                    <span>{pingResult.duration}ms</span>
                  </div>
                  <div className="truncate text-[10px] text-zinc-400 mt-0.5">{pingResult.text}</div>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right: File Preview & Editor */}
        <div className="flex-1 flex flex-col min-w-0 min-h-0 overflow-hidden">
          {/* File Tabs Bar */}
          <div className={`px-4 pt-2 border-b flex items-center justify-between shrink-0 ${
            isDark ? "border-zinc-800 bg-[#141418]" : "border-slate-200 bg-slate-100"
          }`}>
            <div className="flex items-center gap-1.5 overflow-x-auto scrollbar-none">
              <button
                onClick={() => setActiveTab("dockerfile")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "dockerfile"
                    ? isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs"
                    : isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                <FileCode className="w-3.5 h-3.5" />
                <span>Dockerfile</span>
              </button>

              <button
                onClick={() => setActiveTab("compose")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "compose"
                    ? isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs"
                    : isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                <Layers className="w-3.5 h-3.5" />
                <span>docker-compose.yml</span>
              </button>

              <button
                onClick={() => setActiveTab("dockerignore")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "dockerignore"
                    ? isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs"
                    : isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                <ShieldCheck className="w-3.5 h-3.5" />
                <span>.dockerignore</span>
              </button>

              <button
                onClick={() => setActiveTab("devcontainer")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "devcontainer"
                    ? isDark ? "bg-[#101014] text-sky-400 border-t-2 border-sky-500" : "bg-white text-sky-600 border-t-2 border-sky-600 shadow-xs"
                    : isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                <Settings className="w-3.5 h-3.5" />
                <span>devcontainer.json</span>
              </button>

              <button
                onClick={() => setActiveTab("validator")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "validator"
                    ? isDark ? "bg-[#101014] text-emerald-400 border-t-2 border-emerald-500" : "bg-white text-emerald-600 border-t-2 border-emerald-600 shadow-xs"
                    : isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                <span>Hadolint & Security Checks</span>
              </button>

              <button
                onClick={() => setActiveTab("cheatsheet")}
                className={`flex items-center gap-2 px-3 py-2 rounded-t-lg text-xs font-semibold transition-all cursor-pointer ${
                  activeTab === "cheatsheet"
                    ? isDark ? "bg-[#101014] text-amber-400 border-t-2 border-amber-500" : "bg-white text-amber-600 border-t-2 border-amber-600 shadow-xs"
                    : isDark ? "text-zinc-400 hover:text-white" : "text-slate-600 hover:text-slate-900"
                }`}
              >
                <Terminal className="w-3.5 h-3.5" />
                <span>CLI Cheat Sheet</span>
              </button>
            </div>

            {/* Action buttons on tab */}
            {activeTab !== "cheatsheet" && activeTab !== "validator" && (
              <div className="flex items-center gap-2 mb-1">
                <button
                  onClick={handleSaveActiveFile}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-semibold bg-sky-600 hover:bg-sky-500 text-white transition-colors cursor-pointer"
                >
                  {savedStatus === activeTargetFilename ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-300" />
                      <span>Saved!</span>
                    </>
                  ) : (
                    <>
                      <Save className="w-3.5 h-3.5" />
                      <span>Save {activeTargetFilename}</span>
                    </>
                  )}
                </button>

                <button
                  onClick={() => copyToClipboard(activeContent, "active")}
                  className={`flex items-center gap-1 px-2.5 py-1 rounded-md text-xs font-semibold border transition-colors cursor-pointer ${
                    isDark ? "border-zinc-700 bg-zinc-800 text-zinc-300 hover:text-white" : "border-slate-300 bg-white text-slate-700 hover:bg-slate-50"
                  }`}
                >
                  {copiedKey === "active" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedKey === "active" ? "Copied!" : "Copy"}</span>
                </button>
              </div>
            )}
          </div>

          {/* Content Pane */}
          <div className="flex-1 overflow-auto p-4 font-mono text-xs">
            {activeTab === "validator" ? (
              <div className="space-y-4 max-w-3xl font-sans">
                <div className={`p-4 rounded-xl border ${isDark ? "border-zinc-800 bg-[#121216]" : "border-slate-200 bg-white"}`}>
                  <div className="flex items-center justify-between mb-3">
                    <div>
                      <h4 className="font-bold text-sm text-emerald-400 flex items-center gap-2">
                        <ShieldCheck className="w-4 h-4" /> Hadolint & Container Security Audit
                      </h4>
                      <p className="text-xs text-zinc-400">
                        Evaluates Dockerfile, image layering, user privileges, and compose network isolation.
                      </p>
                    </div>
                    <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                      {ruleChecks.filter(r => r.status === "pass").length}/{ruleChecks.length} Passed
                    </span>
                  </div>

                  <div className="space-y-3">
                    {ruleChecks.map(rule => (
                      <div
                        key={rule.id}
                        className={`p-3 rounded-lg border text-xs space-y-1 ${
                          rule.status === "pass"
                            ? isDark ? "bg-emerald-950/20 border-emerald-500/30" : "bg-emerald-50 border-emerald-200"
                            : isDark ? "bg-amber-950/20 border-amber-500/30" : "bg-amber-50 border-amber-200"
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            {rule.status === "pass" ? (
                              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                            ) : (
                              <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
                            )}
                            <span className="font-bold text-zinc-100">{rule.title}</span>
                          </div>
                          <span className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded ${
                            rule.status === "pass" ? "bg-emerald-500/20 text-emerald-300" : "bg-amber-500/20 text-amber-300"
                          }`}>
                            {rule.status}
                          </span>
                        </div>
                        <p className="text-zinc-300 text-[11px] pl-6">{rule.detail}</p>
                        {rule.fixRecommendation && rule.status !== "pass" && (
                          <p className="text-amber-400 text-[10px] pl-6 font-semibold">Tip: {rule.fixRecommendation}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ) : activeTab === "cheatsheet" ? (
              <div className="space-y-4 max-w-3xl font-sans">
                <div className={`p-4 rounded-xl border ${isDark ? "border-zinc-800 bg-[#121216]" : "border-slate-200 bg-white"}`}>
                  <h4 className="font-bold text-sm text-sky-400 mb-2 flex items-center gap-2">
                    <Terminal className="w-4 h-4" /> Docker CLI Production Workflow
                  </h4>
                  <p className="text-xs text-zinc-400 mb-4">
                    Run these commands in your project terminal to build, run, and manage your containers.
                  </p>

                  <div className="space-y-3 font-mono text-xs">
                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">1. Build Docker image with tag:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker build -t my-app:latest .</code>
                        <button onClick={() => copyToClipboard("docker build -t my-app:latest .", "c1")} className="p-1 hover:text-sky-400 cursor-pointer">
                          {copiedKey === "c1" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">2. Run standalone container on port {appPort}:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker run -d -p {appPort}:{appPort} --name my-running-app my-app:latest</code>
                        <button onClick={() => copyToClipboard(`docker run -d -p ${appPort}:${appPort} --name my-running-app my-app:latest`, "c2")} className="p-1 hover:text-sky-400 cursor-pointer">
                          {copiedKey === "c2" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">3. Start all services with Docker Compose:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker-compose up -d --build</code>
                        <button onClick={() => copyToClipboard("docker-compose up -d --build", "c3")} className="p-1 hover:text-sky-400 cursor-pointer">
                          {copiedKey === "c3" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">4. Stream real-time logs:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker-compose logs -f app</code>
                        <button onClick={() => copyToClipboard("docker-compose logs -f app", "c4")} className="p-1 hover:text-sky-400 cursor-pointer">
                          {copiedKey === "c4" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>

                    <div>
                      <span className="text-[11px] font-sans font-semibold text-zinc-400 block mb-1">5. Open interactive shell inside running container:</span>
                      <div className={`p-2.5 rounded-lg flex items-center justify-between border ${isDark ? "bg-black/60 border-zinc-800" : "bg-slate-100 border-slate-300"}`}>
                        <code>docker-compose exec app sh</code>
                        <button onClick={() => copyToClipboard("docker-compose exec app sh", "c5")} className="p-1 hover:text-sky-400 cursor-pointer">
                          {copiedKey === "c5" ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ) : (
              <pre className={`p-4 rounded-xl border leading-relaxed overflow-x-auto whitespace-pre ${
                isDark ? "bg-[#0c0c0e] border-zinc-800 text-zinc-200" : "bg-white border-slate-200 text-slate-800"
              }`}>
                <code>{activeContent}</code>
              </pre>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default DockerDevContainerStudioAgent;
